version: '3'

services:
  backend:
    restart: always
    build: ./dockerfiles/backend
    tty: true
    expose:
      - '8000'
    links:
      - postgres:postgres
    volumes:
      - ./backend:/usr/src/backend
      - ./backend/static:/usr/src/backend/static
    environment:
      DEBUG: 'true'
    command: bash -c "cd /usr/src/backend && /usr/local/bin/gunicorn app.wsgi -b 0.0.0.0:8000"

  frontend:
    build: ./dockerfiles/frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/frontend
    command: sh -c "cd /usr/src/frontend && yarn run serve --port 3000"
    links:
      - backend:backend

  nginx:
    restart: always
    build: ./dockerfiles/nginx
    ports:
      - 80:80
    volumes:
      - ./backend/static:/usr/src/backend/static
    links:
      - backend:backend
      - frontend:frontend

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata: